[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my-backend"
version = "0.0.1"
requires-python = ">=3.8"
keywords = []

[project.entry-points."keyring.backends"]
"jfly backend" = "my_backend"
